-- ============================================================
-- PanaSony Manufacturing Dashboard
-- DAX Measures: Production Domain
-- Version: 1.0 | March 2026
-- Table: Production Analytics
-- ============================================================

-- Total Production Volume
Total Production Volume =
SUM('Production Analytics'[ProductionVolume])

-- Total Good Units
Total Good Units =
SUM('Production Analytics'[GoodUnits])

-- Total Scrap Units
Total Scrap Units =
SUM('Production Analytics'[ScrapUnits])

-- Peak Month (highest average volume month)
Peak Month =
VAR MonthSummary =
    SUMMARIZE(
        'Production Analytics',
        'Production Analytics'[MonthName],
        'Production Analytics'[MonthNumber],
        "MonthVol", SUM('Production Analytics'[ProductionVolume])
    )
VAR PeakVol = MAXX(MonthSummary, [MonthVol])
RETURN
    MAXX(
        FILTER(MonthSummary, [MonthVol] = PeakVol),
        'Production Analytics'[MonthName]
    )
